[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000228_sub-pixar076/fmriprep_wf/single_subject_pixar076_wf/func_preproc_task_pixar_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000228_sub-pixar076/fmriprep_wf/single_subject_pixar076_wf/func_preproc_task_pixar_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000228_sub-pixar076/fmriprep_wf/single_subject_pixar076_wf/func_preproc_task_pixar_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Cloning dataset to Dataset(/scratch1/03201/jbwexler/work_dir/fmriprep/ds000228_sub-pixar076/fmriprep_wf/single_subject_pixar076_wf/func_preproc_task_pixar_wf/unwarp_wf/resample/sourcedata/templateflow) 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000228_sub-pixar076/fmriprep_wf/single_subject_pixar076_wf/func_preproc_task_pixar_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000228_sub-pixar076/fmriprep_wf/single_subject_pixar076_wf/func_preproc_task_pixar_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000228_sub-pixar076/fmriprep_wf/single_subject_pixar076_wf/func_preproc_task_pixar_wf/unwarp_wf/resample/sourcedata/templateflow 
[INFO] Attempting to clone from https://github.com/templateflow/templateflow.git to /scratch1/03201/jbwexler/work_dir/fmriprep/ds000228_sub-pixar076/fmriprep_wf/single_subject_pixar076_wf/func_preproc_task_pixar_wf/unwarp_wf/resample/sourcedata/templateflow 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
    code = _serve_one(child_r, fds,
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
    code = spawn._main(child_r, parent_sentinel)
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/bin/fmriprep", line 5, in <module>
    from fmriprep.cli.run import main
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 25, in <module>
    from .. import config
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/config.py", line 116, in <module>
    from templateflow import __version__ as _tf_ver
  File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>
    from . import api
  File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>
    from .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layout
  File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 53, in <module>
    install(path=str(TF_HOME), source=TF_GITHUB_SOURCE, recursive=True)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
    results = list(results)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
    for r in _process_results(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
    for res in results:
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/install.py", line 381, in __call__
    for r in destination_dataset.get(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
    for r in _process_results(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
    for res in results:
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/get.py", line 849, in __call__
    refds = require_dataset(
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 566, in require_dataset
    if check_installed and not dataset.is_installed():
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 366, in is_installed
    self.repo is not None
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 271, in repo
    self._repo = repo_from_path(self._path)
  File "/opt/conda/lib/python3.8/site-packages/datalad/core/local/repo.py", line 56, in repo_from_path
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 280, in main
    code = _serve_one(child_r, fds,    
code = _serve_one(child_r, fds,
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
  File "/opt/conda/lib/python3.8/multiprocessing/forkserver.py", line 319, in _serve_one
    code = spawn._main(child_r, parent_sentinel)
    code = spawn._main(child_r, parent_sentinel)  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 125, in _main

  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
    prepare(preparation_data)  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare

  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
    _fixup_main_from_path(data['init_main_from_path'])  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path

  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    if not cls.is_valid_repo(path, **ckw):    
main_content = runpy.run_path(main_path,    
  File "/opt/conda/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 670, in is_valid_repo
main_content = runpy.run_path(main_path,  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path

  File "/opt/conda/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,    
return _run_module_code(code, init_globals, run_name,  File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code

  File "/opt/conda/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
    _run_code(code, mod_globals, init_globals,  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code

  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
      File "/opt/conda/bin/fmriprep", line 5, in <module>
exec(code, run_globals)
  File "/opt/conda/bin/fmriprep", line 5, in <module>
    from fmriprep.cli.run import main
    from fmriprep.cli.run import main  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 25, in <module>

  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/run.py", line 25, in <module>
    from .. import config    
from .. import config
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/config.py", line 116, in <module>
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/config.py", line 116, in <module>
        from templateflow import __version__ as _tf_ver
from templateflow import __version__ as _tf_ver  File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>

  File "/opt/conda/lib/python3.8/site-packages/templateflow/__init__.py", line 19, in <module>
    from . import api
  File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>
    from . import api
  File "/opt/conda/lib/python3.8/site-packages/templateflow/api.py", line 7, in <module>
    from .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layout
  File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 53, in <module>
    from .conf import TF_LAYOUT, TF_S3_ROOT, TF_USE_DATALAD, requires_layout
  File "/opt/conda/lib/python3.8/site-packages/templateflow/conf/__init__.py", line 53, in <module>
    install(path=str(TF_HOME), source=TF_GITHUB_SOURCE, recursive=True)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
    install(path=str(TF_HOME), source=TF_GITHUB_SOURCE, recursive=True)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 484, in eval_func
    return return_func(generator_func)(*args, **kwargs)
      File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
return return_func(generator_func)(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
    results = list(results)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
    results = list(results)
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
    for r in _process_results(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
    for r in _process_results(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
    for res in results:
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/install.py", line 381, in __call__
    for res in results:
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/install.py", line 381, in __call__
    for r in destination_dataset.get(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
    for r in destination_dataset.get(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
    for r in _process_results(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
    for r in _process_results(
  File "/opt/conda/lib/python3.8/site-packages/datalad/interface/utils.py", line 579, in _process_results
    for res in results:
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/get.py", line 849, in __call__
    for res in results:
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/get.py", line 849, in __call__
    refds = require_dataset(
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 567, in require_dataset
    refds = require_dataset(
  File "/opt/conda/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 567, in require_dataset
    raise ValueError(u"No installed dataset found at "
ValueError:     raise ValueError(u"No installed dataset found at "No installed dataset found at /scratch1/03201/jbwexler/work_dir/fmriprep/ds000228_sub-pixar076/fmriprep_wf/single_subject_pixar076_wf/func_preproc_task_pixar_wf/unwarp_wf/resample/sourcedata/templateflow.

ValueError: No installed dataset found at /scratch1/03201/jbwexler/work_dir/fmriprep/ds000228_sub-pixar076/fmriprep_wf/single_subject_pixar076_wf/func_preproc_task_pixar_wf/unwarp_wf/resample/sourcedata/templateflow.
    return initialized_annex or GitRepo(path, create=False, init=False).is_with_annex()
  File "/opt/conda/lib/python3.8/site-packages/datalad/support/gitrepo.py", line 1120, in is_with_annex
    return any(
  File "/opt/conda/lib/python3.8/site-packages/datalad/support/gitrepo.py", line 1120, in <genexpr>
    return any(
  File "/opt/conda/lib/python3.8/site-packages/datalad/dataset/gitrepo.py", line 503, in for_each_ref_
    for line in self.call_git_items_(cmd, read_only=True):
  File "/opt/conda/lib/python3.8/site-packages/datalad/dataset/gitrepo.py", line 343, in call_git_items_
    out, _ = self._call_git(args, files, expect_stderr=expect_stderr,
  File "/opt/conda/lib/python3.8/site-packages/datalad/dataset/gitrepo.py", line 259, in _call_git
    res = runner.run(
  File "/opt/conda/lib/python3.8/site-packages/datalad/runner/runner.py", line 145, in run
    raise CommandError(
datalad.runner.exception.CommandError: CommandError: 'git -c diff.ignoreSubmodules=none for-each-ref '--format=%(refname:strip=2)' refs/heads refs/remotes' failed with exitcode 128 under /scratch1/03201/jbwexler/work_dir/fmriprep/ds000228_sub-pixar076/fmriprep_wf/single_subject_pixar076_wf/func_preproc_task_pixar_wf/unwarp_wf/resample/sourcedata/templateflow [err: 'fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).']
